### ISSUE TITLE
ModuleNotFoundError: No module named 'SBEnvironment'

### ISSUE THREAD

**Issue by RodgerLuo** [phy-q/benchmark#3]
I was trying to run `./TestPythonHeuristicAgent.sh RandomAgent` and got this error `ModuleNotFoundError: No module named SBEnvironment`. 

I've tested on both Ubuntu and MacOS and it seems the error is cross-platform.

**Comment by Cheng-Xue** [comment]
Hi Rodger, sorry for the late reply. The issue is fixed, please try again on Ubuntu.

**Comment by RodgerLuo** [comment]
Thanks, Cheng! The `ModuleNotFoundError: No module named SBEnvironment` issue goes away. 

However, a new issue comes up after several agent runs:

```
running 1_01_01
agent 1 running
agent 2 running
agent 3 running
agent 4 running
agent 5 running
agent 6 running
agent 7 running
agent 8 running
2021-11-29 19:50:23,829 - Environment Wrapper - CRITICAL - Error in client-server communication: [Errno 111] Connection refused
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/RL-AngryBirds/sciencebirdsagents/HeuristicAgents/HeuristicAgentThread.py", line 24, in run
    state_representation_type=self.agent.state_representation_type)
  File "/home/ubuntu/RL-AngryBirds/sciencebirdsagents/SBEnvironment/SBEnvironmentWrapper.py", line 83, in make
    info = self.agent.ar.configure(self.agent.id)
  File "/home/ubuntu/RL-AngryBirds/sciencebirdsagents/Client/agent_client.py", line 171, in configure
    self.playing_mode.value
  File "/home/ubuntu/RL-AngryBirds/sciencebirdsagents/Client/agent_client.py", line 131, in _send_command
    self.server_socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
```
That might be related to #4

**Comment by Cheng-Xue** [comment]
it seems like the game server is not initialized. can u try to go to _sciencebirdsgames/Linux_ and run `java -jar ./game_playing_interface.jar` first before running the agent? is the server successfully initialized? if not please also check if you are using java 13. Thanks.

**Comment by RodgerLuo** [comment]
Thanks, Cheng. The issue went away after initializing the server by `java -jar ./game_playing_interface.jar`. 

Closing the issue.
